theme: jekyll-theme-chirpy
lang: en
timezone: America/Bogota

title: "Darwin's architecture blog — featuring bisslog"
tagline: Clean, pluggable microservices in Python (and beyond)
description: >-
  A blog about domain-driven architecture, microservices, and building frameworks that scale.

url: "https://darwinhc.github.io"

github:
  username: darwinhc

social:
  name: Darwin
  email: darwinsherrerac@gmail.com
  links:
    - https://github.com/darwinhc

theme_mode: dark
avatar: /assets/brand/bisslog-logo-imagotipo.png
favicon: /assets/brand/bisslog_symbol_32.png
social_preview_image: /assets/brand/bisslog-logo-imagotipo.png
